parameters:
- name: UpdatePowerBIDatasetTableSchema
  displayName: Update the Power BI Table schema to the latest schema
  default: true
  type: boolean

- name: DeleteAllOrganizationData
  displayName: Delete all data in the Simeon Power BI dataset
  default: true
  type: boolean

- name: InstallPowerBIReport
  displayName: Install or reinstall the Power BI report
  default: true
  type: boolean

- name: BackfillHours
  displayName: Number of hours to include in backfill
  default: 72
  type: number

variables:
- group: Sync
name: $(Date:yyyyMMdd)$(Rev:.r)
trigger: none
pool:
  vmImage: windows-latest
resources:
  repositories:
    - repository: Templates
    type: github
    name: simeoncloud/AzurePipelineTemplates
    ref: refs/heads/feature/SD-929
    endpoint: simeoncloud
  - repository: Reporting
    type: github
    name: simeoncloud/reporting
    ref: refs/heads/feature/installReport
    endpoint: simeoncloud
jobs:
- job: Job
  timeoutInMinutes: 600
  steps:
  - template: BackfillPowerBI.yml@Templates