parameters:
- name: DeleteAllOrganizationData
  displayName: Delete all data in the Simeon Power BI dataset
  default: true
  type: boolean

- name: BackfillOnlyFailedUploadToPowerBISteps
  displayName: Backfill only failed upload to Power BI steps
  default: false
  type: boolean

- name: BackfillHours
  displayName: Number of hours to include in backfill
  default: 72
  type: number

- name: NumberOfParallelPipelinesToBackfill
  displayName: Number of parallel pipelines to backfill
  default: 1
  type: number

variables:
- group: Sync
name: $(Date:yyyyMMdd)$(Rev:.r)
trigger: none
pool:
  vmImage: windows-latest
resources:
  repositories:
  - repository: Templates
    type: github
    name: simeoncloud/AzurePipelineTemplates
    ref: refs/heads/feature/SD-199
    endpoint: simeoncloud
  - repository: Reporting
    type: github
    name: simeoncloud/feature/SD-199
    ref: refs/heads/feature/installReport
    endpoint: simeoncloud
jobs:
- job: Job
  timeoutInMinutes: 600
  steps:
  - template: BackfillPowerBI.yml@Templates
    parameters:
      DeleteAllOrganizationData: ${{ parameters.DeleteAllOrganizationData }}
      BackfillOnlyFailedUploadToPowerBISteps: ${{ parameters.BackfillOnlyFailedUploadToPowerBISteps }}
      BackfillHours: ${{ parameters.BackfillHours }}
      NumberOfParallelPipelinesToBackfill:  ${{ parameters.NumberOfParallelPipelinesToBackfill }}
