parameters:
- name: BackfillOnlyFailedUploadToPowerBISteps
  displayName: Backfill only failed upload to Power BI steps
  default: false
  type: boolean

- name: InstallPowerBIReport
  displayName: Install or reinstall Simeon Power BI report(s)
  default: true
  type: boolean

- name: BackfillHours
  displayName: Number of hours to include in backfill
  default: 72
  type: number

- name: NumberOfParallelPipelinesToBackfill
  displayName: Number of parallel pipelines to backfill
  default: 5
  type: number

variables:
- group: Sync
name: $(Date:yyyyMMdd)$(Rev:.r)
trigger: none
pool:
  vmImage: windows-latest
resources:
  repositories:
  - repository: Templates
    type: github
    name: simeoncloud/AzurePipelineTemplates
    ref: refs/heads/master
    endpoint: simeoncloud
  - repository: Reporting
    type: github
    name: simeoncloud/reporting
    ref: refs/heads/main
    endpoint: simeoncloud
jobs:
- job: Job
  timeoutInMinutes: 600
  steps:
  - template: BackfillPowerBI.yml@Templates
    parameters:
      InstallPowerBIReport: ${{ parameters.InstallPowerBIReport }}
      BackfillOnlyFailedUploadToPowerBISteps: ${{ parameters.BackfillOnlyFailedUploadToPowerBISteps }}
      BackfillHours: ${{ parameters.BackfillHours }}
      NumberOfParallelPipelinesToBackfill:  ${{ parameters.NumberOfParallelPipelinesToBackfill }}
